// <auto-generated />
using System;
using DatalexionBackend.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatalexionBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasFilter("[PhotoId] IS NOT NULL");

                    b.ToTable("Candidate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(353),
                            Name = "Álvaro Delgado",
                            PhotoId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(353)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(355),
                            Name = "Laura Raffo",
                            PhotoId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(356)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(357),
                            Name = "Jorge Gandini",
                            PhotoId = 3,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(357)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(358),
                            Name = "Juan Sartori",
                            PhotoId = 4,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(358)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(359),
                            Name = "Yamandú Orsi",
                            PhotoId = 5,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(360)
                        },
                        new
                        {
                            Id = 6,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(360),
                            Name = "Carolina Cosse",
                            PhotoId = 6,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(361)
                        },
                        new
                        {
                            Id = 7,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(362),
                            Name = "Mario Bergara",
                            PhotoId = 7,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(362)
                        },
                        new
                        {
                            Id = 8,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(363),
                            Name = "Pablo Mieres",
                            PhotoId = 8,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(363)
                        },
                        new
                        {
                            Id = 9,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(364),
                            Name = "Edgardo Novick",
                            PhotoId = 9,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(365)
                        },
                        new
                        {
                            Id = 10,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(365),
                            Name = "Andrés Lima",
                            PhotoId = 10,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(366)
                        },
                        new
                        {
                            Id = 11,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(367),
                            Name = "Gabriel Gurméndez",
                            PhotoId = 11,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(367)
                        },
                        new
                        {
                            Id = 12,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(368),
                            Name = "Robert Silva",
                            PhotoId = 12,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(368)
                        },
                        new
                        {
                            Id = 13,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(369),
                            Name = "Andrés Ojeda",
                            PhotoId = 13,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(370)
                        },
                        new
                        {
                            Id = 14,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(371),
                            Name = "Gustavo Zubía",
                            PhotoId = 14,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(371)
                        },
                        new
                        {
                            Id = 15,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(372),
                            Name = "Guzmán Acosta y Lara",
                            PhotoId = 15,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(373)
                        },
                        new
                        {
                            Id = 16,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(373),
                            Name = "Tabaré Viera",
                            PhotoId = 16,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(374)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("MunicipalityId1");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitDelegado", b =>
                {
                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<int>("DelegadoId")
                        .HasColumnType("int");

                    b.HasKey("CircuitId", "DelegadoId");

                    b.HasIndex("DelegadoId");

                    b.ToTable("CircuitDelegado");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitParty", b =>
                {
                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("BlankVotes")
                        .HasColumnType("int");

                    b.Property<int>("ImagesUploadedCount")
                        .HasColumnType("int");

                    b.Property<int?>("LastUpdateDelegadoId")
                        .HasColumnType("int");

                    b.Property<int>("NullVotes")
                        .HasColumnType("int");

                    b.Property<int>("ObservedVotes")
                        .HasColumnType("int");

                    b.Property<int>("RecurredVotes")
                        .HasColumnType("int");

                    b.Property<bool>("Step1completed")
                        .HasColumnType("bit");

                    b.Property<bool>("Step2completed")
                        .HasColumnType("bit");

                    b.Property<bool>("Step3completed")
                        .HasColumnType("bit");

                    b.Property<int?>("TotalPartyVotes")
                        .HasColumnType("int");

                    b.HasKey("CircuitId", "PartyId");

                    b.HasIndex("PartyId");

                    b.ToTable("CircuitParty");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitSlate", b =>
                {
                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<int>("SlateId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSlateVotes")
                        .HasColumnType("int");

                    b.HasKey("CircuitId", "SlateId");

                    b.HasIndex("SlateId");

                    b.ToTable("CircuitSlate");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Frente Amplio",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(734),
                            Name = "Frente Amplio",
                            PartyId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(735)
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Partido Nacional",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(738),
                            Name = "Partido Nacional",
                            PartyId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(738)
                        },
                        new
                        {
                            Id = 3,
                            Comments = "Partido Colorado",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(741),
                            Name = "Partido Colorado",
                            PartyId = 3,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(741)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Delegado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Delegado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CI = "11111111",
                            ClientId = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(776),
                            Email = "gonzalo.delegado@datalexion.lat",
                            Name = "Gonzalo",
                            Phone = "099415831",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(776)
                        },
                        new
                        {
                            Id = 2,
                            CI = "12345678",
                            ClientId = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(779),
                            Email = "diego.delegado@datalexion.lat",
                            Name = "Diego",
                            Phone = "099589896",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(779)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegadoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DelegadoId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SlateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SlateId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PhotoLongId")
                        .HasColumnType("int");

                    b.Property<int?>("PhotoShortId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhotoLongId")
                        .IsUnique()
                        .HasFilter("[PhotoLongId] IS NOT NULL");

                    b.HasIndex("PhotoShortId")
                        .IsUnique()
                        .HasFilter("[PhotoShortId] IS NOT NULL");

                    b.ToTable("Party");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3153dd",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(650),
                            Name = "Frente Amplio",
                            PhotoLongId = 101,
                            PhotoShortId = 111,
                            ShortName = "FA",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(651)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3153dd",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(657),
                            Name = "Partido Nacional",
                            PhotoLongId = 102,
                            PhotoShortId = 112,
                            ShortName = "PN",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(657)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#d62929",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(659),
                            Name = "Partido Colorado",
                            PhotoLongId = 103,
                            PhotoShortId = 113,
                            ShortName = "PC",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(660)
                        },
                        new
                        {
                            Id = 4,
                            Color = "#b929d6",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(661),
                            Name = "Partido Independiente",
                            PhotoLongId = 104,
                            PhotoShortId = 114,
                            ShortName = "PI",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(661)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#f9bb28",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(663),
                            Name = "Cabildo Abierto",
                            PhotoLongId = 105,
                            PhotoShortId = 115,
                            ShortName = "CA",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(663)
                        },
                        new
                        {
                            Id = 6,
                            Color = "#009001",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(664),
                            Name = "PERI",
                            PhotoLongId = 106,
                            PhotoShortId = 116,
                            ShortName = "PERI",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(665)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int?>("CandidateId1")
                        .HasColumnType("int");

                    b.Property<int?>("CircuitId")
                        .HasColumnType("int");

                    b.Property<int?>("CircuitId1")
                        .HasColumnType("int");

                    b.Property<int?>("CircuitPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartyLongId")
                        .HasColumnType("int");

                    b.Property<int?>("PartyShortId")
                        .HasColumnType("int");

                    b.Property<int?>("SlateId")
                        .HasColumnType("int");

                    b.Property<int?>("SlateId1")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WingId")
                        .HasColumnType("int");

                    b.Property<int?>("WingId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId1");

                    b.HasIndex("PartyLongId");

                    b.HasIndex("PartyShortId");

                    b.HasIndex("SlateId1");

                    b.HasIndex("WingId1");

                    b.HasIndex("CircuitId1", "CircuitPartyId");

                    b.ToTable("Photo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9819),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo1.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9830)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9848),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo1.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9849)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9850),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo3.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9851)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9852),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo4.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9853)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9854),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo5.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9854)
                        },
                        new
                        {
                            Id = 6,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9864),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo6.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9864)
                        },
                        new
                        {
                            Id = 7,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9865),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo7.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9866)
                        },
                        new
                        {
                            Id = 8,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9867),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo8.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9868)
                        },
                        new
                        {
                            Id = 9,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9869),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo9.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9869)
                        },
                        new
                        {
                            Id = 10,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9872),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo10.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 36, DateTimeKind.Local).AddTicks(9873)
                        },
                        new
                        {
                            Id = 11,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(17),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo11.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(17)
                        },
                        new
                        {
                            Id = 12,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(18),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo12.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(19)
                        },
                        new
                        {
                            Id = 13,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(20),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo13.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(38)
                        },
                        new
                        {
                            Id = 14,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(52),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo14.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(53)
                        },
                        new
                        {
                            Id = 15,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(54),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo15.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(54)
                        },
                        new
                        {
                            Id = 16,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(56),
                            URL = "https://cienciasdesofa.lat/uploads/candidates/photo16.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(56)
                        },
                        new
                        {
                            Id = 101,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(594),
                            URL = "https://cienciasdesofa.lat/uploads/partiesLong/photo101.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(595)
                        },
                        new
                        {
                            Id = 102,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(598),
                            URL = "https://cienciasdesofa.lat/uploads/partiesLong/photo102.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(598)
                        },
                        new
                        {
                            Id = 103,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(600),
                            URL = "https://cienciasdesofa.lat/uploads/partiesLong/photo103.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(600)
                        },
                        new
                        {
                            Id = 104,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(602),
                            URL = "https://cienciasdesofa.lat/uploads/partiesLong/photo104.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(602)
                        },
                        new
                        {
                            Id = 105,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(603),
                            URL = "https://cienciasdesofa.lat/uploads/partiesLong/photo105.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(604)
                        },
                        new
                        {
                            Id = 106,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(606),
                            URL = "https://cienciasdesofa.lat/uploads/partiesLong/photo106.jpg",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(607)
                        },
                        new
                        {
                            Id = 111,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(608),
                            URL = "https://cienciasdesofa.lat/uploads/partiesShort/photo111.png",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(608)
                        },
                        new
                        {
                            Id = 112,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(609),
                            URL = "https://cienciasdesofa.lat/uploads/partiesShort/photo112.png",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(610)
                        },
                        new
                        {
                            Id = 113,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(611),
                            URL = "https://cienciasdesofa.lat/uploads/partiesShort/photo113.png",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(612)
                        },
                        new
                        {
                            Id = 114,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(619),
                            URL = "https://cienciasdesofa.lat/uploads/partiesShort/photo114.png",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(619)
                        },
                        new
                        {
                            Id = 115,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(620),
                            URL = "https://cienciasdesofa.lat/uploads/partiesShort/photo115.png",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(621)
                        },
                        new
                        {
                            Id = 116,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(622),
                            URL = "https://cienciasdesofa.lat/uploads/partiesShort/photo116.png",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(622)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Center")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Zoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(957),
                            Name = "Montevideo",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(957)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(958),
                            Name = "Canelones",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(959)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(959),
                            Name = "Maldonado",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(960)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(961),
                            Name = "Rocha",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(961)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(962),
                            Name = "Colonia",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(962)
                        },
                        new
                        {
                            Id = 6,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(963),
                            Name = "Artigas",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(963)
                        },
                        new
                        {
                            Id = 7,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(964),
                            Name = "Salto",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(964)
                        },
                        new
                        {
                            Id = 8,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(965),
                            Name = "Paysandú",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(965)
                        },
                        new
                        {
                            Id = 9,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(966),
                            Name = "Tacuarembó",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(966)
                        },
                        new
                        {
                            Id = 10,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(967),
                            Name = "Rivera",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(968)
                        },
                        new
                        {
                            Id = 11,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(968),
                            Name = "San José",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(969)
                        },
                        new
                        {
                            Id = 12,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(969),
                            Name = "Durazno",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(970)
                        },
                        new
                        {
                            Id = 13,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(970),
                            Name = "Treinta y Tres",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(971)
                        },
                        new
                        {
                            Id = 14,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(971),
                            Name = "Cerro Largo",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(972)
                        },
                        new
                        {
                            Id = 15,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(972),
                            Name = "Rivera",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(973)
                        },
                        new
                        {
                            Id = 16,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(974),
                            Name = "Flores",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(974)
                        },
                        new
                        {
                            Id = 17,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(975),
                            Name = "Florida",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(975)
                        },
                        new
                        {
                            Id = 18,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(976),
                            Name = "Lavalleja",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(976)
                        },
                        new
                        {
                            Id = 19,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(977),
                            Name = "Soriano",
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(977)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Slate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Votes")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasFilter("[PhotoId] IS NOT NULL");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("WingId");

                    b.ToTable("Slate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateId = 6,
                            Color = "#3153dd",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(449),
                            Name = "5005",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(449),
                            WingId = 1
                        },
                        new
                        {
                            Id = 2,
                            CandidateId = 5,
                            Color = "#3153dd",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(455),
                            Name = "711",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(455),
                            WingId = 1
                        },
                        new
                        {
                            Id = 3,
                            CandidateId = 6,
                            Color = "#d62929",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(457),
                            Name = "90",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(457),
                            WingId = 1
                        },
                        new
                        {
                            Id = 4,
                            CandidateId = 5,
                            Color = "#b929d6",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(459),
                            Name = "609",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(459),
                            WingId = 1
                        },
                        new
                        {
                            Id = 5,
                            CandidateId = 1,
                            Color = "#bec11a",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(467),
                            Name = "71",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(467),
                            WingId = 2
                        },
                        new
                        {
                            Id = 6,
                            CandidateId = 1,
                            Color = "#3153dd",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(469),
                            Name = "404",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(469),
                            WingId = 2
                        },
                        new
                        {
                            Id = 7,
                            CandidateId = 2,
                            Color = "#ff0000",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(470),
                            Name = "40",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(471),
                            WingId = 2
                        },
                        new
                        {
                            Id = 8,
                            CandidateId = 2,
                            Color = "#00ff00",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(473),
                            Name = "250",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(473),
                            WingId = 2
                        },
                        new
                        {
                            Id = 9,
                            CandidateId = 2,
                            Color = "#0000ff",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(474),
                            Name = "880",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(475),
                            WingId = 2
                        },
                        new
                        {
                            Id = 10,
                            CandidateId = 11,
                            Color = "#ff00ff",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(476),
                            Name = "15",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(476),
                            WingId = 3
                        },
                        new
                        {
                            Id = 11,
                            CandidateId = 12,
                            Color = "#987654",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(478),
                            Name = "85",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(478),
                            WingId = 3
                        },
                        new
                        {
                            Id = 12,
                            CandidateId = 12,
                            Color = "#abcdef",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(479),
                            Name = "1",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(480),
                            WingId = 3
                        },
                        new
                        {
                            Id = 13,
                            CandidateId = 12,
                            Color = "#fedcba",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(481),
                            Name = "2000",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(481),
                            WingId = 3
                        },
                        new
                        {
                            Id = 14,
                            CandidateId = 11,
                            Color = "#012345",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(482),
                            Name = "1515",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(483),
                            WingId = 3
                        },
                        new
                        {
                            Id = 15,
                            CandidateId = 11,
                            Color = "#012345",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(484),
                            Name = "600",
                            ProvinceId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(485),
                            WingId = 3
                        },
                        new
                        {
                            Id = 16,
                            CandidateId = 5,
                            Color = "#abcdef",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(486),
                            Name = "500",
                            ProvinceId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(486),
                            WingId = 1
                        },
                        new
                        {
                            Id = 17,
                            CandidateId = 5,
                            Color = "#fedcba",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(487),
                            Name = "123",
                            ProvinceId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(488),
                            WingId = 1
                        },
                        new
                        {
                            Id = 18,
                            CandidateId = 5,
                            Color = "#012345",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(489),
                            Name = "999",
                            ProvinceId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(489),
                            WingId = 1
                        },
                        new
                        {
                            Id = 19,
                            CandidateId = 5,
                            Color = "#abcdef",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(491),
                            Name = "777",
                            ProvinceId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(491),
                            WingId = 1
                        },
                        new
                        {
                            Id = 20,
                            CandidateId = 1,
                            Color = "#fedcba",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(492),
                            Name = "333",
                            ProvinceId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(493),
                            WingId = 2
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Wing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasFilter("[PhotoId] IS NOT NULL");

                    b.ToTable("Wing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(863),
                            Name = "FA",
                            PartyId = 1,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(863)
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(867),
                            Name = "PN",
                            PartyId = 2,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(868)
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(909),
                            Name = "PC",
                            PartyId = 3,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(910)
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(911),
                            Name = "PI",
                            PartyId = 4,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(911)
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(912),
                            Name = "CA",
                            PartyId = 5,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(912)
                        },
                        new
                        {
                            Id = 6,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(913),
                            Name = "PERI",
                            PartyId = 6,
                            Update = new DateTime(2024, 4, 22, 0, 53, 46, 37, DateTimeKind.Local).AddTicks(914)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ClaimType = "role",
                            ClaimValue = "Admin",
                            UserId = "8498a3ff-ca69-4b93-9a37-49a73c8dec77"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "role",
                            ClaimValue = "Analyst",
                            UserId = "ddc18aa2-c5c7-40c9-9db3-246d2a05a06c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8498a3ff-ca69-4b93-9a37-49a73c8dec77",
                            RoleId = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c"
                        },
                        new
                        {
                            UserId = "ddc18aa2-c5c7-40c9-9db3-246d2a05a06c",
                            RoleId = "bef4cbd4-1f2b-472f-a3f2-e1a901f6811c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.IdentityEntities.DatalexionRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("DatalexionRole");

                    b.HasData(
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a1e2-e1a901f6808c",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 45, 373, DateTimeKind.Local).AddTicks(5465),
                            Update = new DateTime(2024, 4, 22, 0, 53, 45, 373, DateTimeKind.Local).AddTicks(5466)
                        },
                        new
                        {
                            Id = "bef4cbd4-1f2b-472f-a3f2-e1a901f6811c",
                            Name = "Analyst",
                            NormalizedName = "ANALYST",
                            Creation = new DateTime(2024, 4, 22, 0, 53, 45, 373, DateTimeKind.Local).AddTicks(5478),
                            Update = new DateTime(2024, 4, 22, 0, 53, 45, 373, DateTimeKind.Local).AddTicks(5479)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.IdentityEntities.DatalexionUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Update")
                        .HasColumnType("datetime2");

                    b.HasIndex("ClientId");

                    b.HasDiscriminator().HasValue("DatalexionUser");

                    b.HasData(
                        new
                        {
                            Id = "8498a3ff-ca69-4b93-9a37-49a73c8dec77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d08cfe27-f3e3-4e79-ba20-51ee81afb81e",
                            Email = "adminpn@datalexion.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINPN@DATALEXION.LAT",
                            NormalizedUserName = "ADMINPN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGKOPyIVvlsw52AUp31drcMQ5oJ3SlUdSkR/ZR9g3AIQKdaWzFzQftAgWtfKctIBpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "847b9312-777d-46e4-8a9e-5c054facbf5c",
                            TwoFactorEnabled = false,
                            UserName = "adminpn",
                            ClientId = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 45, 518, DateTimeKind.Local).AddTicks(5580),
                            Name = "Admin PN",
                            Update = new DateTime(2024, 4, 22, 0, 53, 45, 518, DateTimeKind.Local).AddTicks(5599)
                        },
                        new
                        {
                            Id = "ddc18aa2-c5c7-40c9-9db3-246d2a05a06c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5be0158f-473b-4e38-8767-5f1026c27e96",
                            Email = "normal@datalexion.lat",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NORMAL@DATALEXION.LAT",
                            NormalizedUserName = "ANALYSTPN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFfrEooZfDBYa/j7IdJAsW/oavYwNDhSpuRr7faSJ44+kjOqEo4k4qw+t8Y+RtdwFQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1759d6dd-9901-44aa-9cb5-d4669c6c7123",
                            TwoFactorEnabled = false,
                            UserName = "analystpn",
                            ClientId = 2,
                            Creation = new DateTime(2024, 4, 22, 0, 53, 45, 847, DateTimeKind.Local).AddTicks(8456),
                            Name = "Analista PN",
                            Update = new DateTime(2024, 4, 22, 0, 53, 45, 847, DateTimeKind.Local).AddTicks(8467)
                        });
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Photo", "Photo")
                        .WithOne()
                        .HasForeignKey("DatalexionBackend.Core.Domain.Entities.Candidate", "PhotoId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Circuit", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Municipality", null)
                        .WithMany("ListCircuits")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitDelegado", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Circuit", "Circuit")
                        .WithMany("ListCircuitDelegados")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Delegado", "Delegado")
                        .WithMany("ListCircuitDelegados")
                        .HasForeignKey("DelegadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Delegado");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitParty", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Circuit", "Circuit")
                        .WithMany("ListCircuitParties")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Party", "Party")
                        .WithMany("ListCircuitParties")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitSlate", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Circuit", "Circuit")
                        .WithMany("ListCircuitSlates")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Slate", "Slate")
                        .WithMany("ListCircuitSlates")
                        .HasForeignKey("SlateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Slate");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Client", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Delegado", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Client", "Client")
                        .WithMany("ListDelegados")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Delegado", "Delegado")
                        .WithMany("ListMunicipalities")
                        .HasForeignKey("DelegadoId");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Province", "Province")
                        .WithMany("ListMunicipalities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delegado");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Participant", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Slate", "Slate")
                        .WithMany("ListParticipants")
                        .HasForeignKey("SlateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Slate");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Party", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Photo", "PhotoLong")
                        .WithOne()
                        .HasForeignKey("DatalexionBackend.Core.Domain.Entities.Party", "PhotoLongId");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Photo", "PhotoShort")
                        .WithOne()
                        .HasForeignKey("DatalexionBackend.Core.Domain.Entities.Party", "PhotoShortId");

                    b.Navigation("PhotoLong");

                    b.Navigation("PhotoShort");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Photo", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId1");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Party", "PartyLong")
                        .WithMany()
                        .HasForeignKey("PartyLongId");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Party", "PartyShort")
                        .WithMany()
                        .HasForeignKey("PartyShortId");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Slate", "Slate")
                        .WithMany()
                        .HasForeignKey("SlateId1");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Wing", "Wing")
                        .WithMany()
                        .HasForeignKey("WingId1");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.CircuitParty", "Circuit")
                        .WithMany("ListPhotos")
                        .HasForeignKey("CircuitId1", "CircuitPartyId");

                    b.Navigation("Candidate");

                    b.Navigation("Circuit");

                    b.Navigation("PartyLong");

                    b.Navigation("PartyShort");

                    b.Navigation("Slate");

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Slate", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Photo", "Photo")
                        .WithOne()
                        .HasForeignKey("DatalexionBackend.Core.Domain.Entities.Slate", "PhotoId");

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Province", "Province")
                        .WithMany("ListSlates")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Wing", "Wing")
                        .WithMany("ListSlates")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Photo");

                    b.Navigation("Province");

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Wing", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Party", "Party")
                        .WithMany("ListWings")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Photo", "Photo")
                        .WithOne()
                        .HasForeignKey("DatalexionBackend.Core.Domain.Entities.Wing", "PhotoId");

                    b.Navigation("Party");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.IdentityEntities.DatalexionUser", b =>
                {
                    b.HasOne("DatalexionBackend.Core.Domain.Entities.Client", "Client")
                        .WithMany("ListUsers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Circuit", b =>
                {
                    b.Navigation("ListCircuitDelegados");

                    b.Navigation("ListCircuitParties");

                    b.Navigation("ListCircuitSlates");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.CircuitParty", b =>
                {
                    b.Navigation("ListPhotos");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Client", b =>
                {
                    b.Navigation("ListDelegados");

                    b.Navigation("ListUsers");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Delegado", b =>
                {
                    b.Navigation("ListCircuitDelegados");

                    b.Navigation("ListMunicipalities");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Municipality", b =>
                {
                    b.Navigation("ListCircuits");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Party", b =>
                {
                    b.Navigation("ListCircuitParties");

                    b.Navigation("ListWings");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Province", b =>
                {
                    b.Navigation("ListMunicipalities");

                    b.Navigation("ListSlates");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Slate", b =>
                {
                    b.Navigation("ListCircuitSlates");

                    b.Navigation("ListParticipants");
                });

            modelBuilder.Entity("DatalexionBackend.Core.Domain.Entities.Wing", b =>
                {
                    b.Navigation("ListSlates");
                });
#pragma warning restore 612, 618
        }
    }
}
