const apiURL = process.env.REACT_APP_API_URL;

export const apiVersionName = process.env.REACT_APP_API_VERSION_NAME;
export const apiVersionNumber = process.env.REACT_APP_API_VERSION_NUMBER;
export const urlAccount = `${apiURL}/accounts`;
export const urlLoginGeneral = `${apiURL}/accounts/LoginGeneral`;
export const urlLoginDelegados = `${apiURL}/accounts/LoginDelegados`;
export const urlCircuit = `${apiURL}/circuits`;
export const urlCircuitUpdate = `${apiURL}/circuits/UpdateCircuit`; // No usar, usar PUT directo al Controller
export const urlClient = `${apiURL}/clients`;
export const urlDelegado = `${apiURL}/delegados`;
export const urlCandidate = `${apiURL}/candidates`;
export const urlParty = `${apiURL}/parties`;
export const urlMyParty = `${apiURL}/parties`;
export const urlProvince = `${apiURL}/provinces`;
export const urlMunicipality = `${apiURL}/municipalities`;
export const urlWing = `${apiURL}/wings`;
export const urlSlate = `${apiURL}/slates`;
export const urlUserRole = `${apiURL}/accounts`;
export const urlAccountRegister = `${apiURL}/accounts/CreateUser`; // No usar, usar POST directo al Controller
export const urlAccountUpdateUser = `${apiURL}/accounts/UpdateUser`; // No usar, usar PUT directo al Controller
export const urlUserRoleCreate = `${apiURL}/accounts/CreateUserRole`; // No usar, usar POST directo al Controller
export const urlUserRoleUpdate = `${apiURL}/accounts/UpdateUserRole`; // No usar, usar PUT directo al Controller
export const urlIsCIAlreadyRegistered = `${apiURL}/delegados/IsCIAlreadyRegistered`;
export const urlIsUsernameAlreadyRegistered = `${apiURL}/accounts/IsUsernameAlreadyRegistered`;
